2025-03-05 18:54:46,326 - pyfame.debug - ERROR - pyfame.py:87 - process_frame - Function encountered a FaceNotFoundError attempting to call FaceMesh.process().
2025-03-05 18:54:46,344 - pyfame.debug - ERROR - pyfame.py:641 - mask_face_region - Function has encountered an unparseable file type .webp. Consider using different input file formats, or transcoding video files with pyfameutils.transcode_video_to_mp4().
2025-03-05 19:00:44,592 - pyfame.debug - ERROR - pyfame.py:91 - process_frame - Function encountered a FaceNotFoundError attempting to call FaceMesh.process().
2025-03-05 19:00:44,610 - pyfame.debug - ERROR - pyfame.py:645 - mask_face_region - Function has encountered an unparseable file type .webp. Consider using different input file formats, or transcoding video files with pyfameutils.transcode_video_to_mp4().
2025-03-05 19:04:13,040 - pyfame.debug - ERROR - pyfame.py:91 - process_frame - Function encountered a FaceNotFoundError attempting to call FaceMesh.process().
2025-03-05 19:04:13,053 - pyfame.debug - ERROR - pyfame.py:645 - mask_face_region - Function has encountered an unparseable file type .webp. Consider using different input file formats, or transcoding video files with pyfameutils.transcode_video_to_mp4().
2025-03-05 19:04:33,271 - pyfame.debug - ERROR - pyfame.py:91 - process_frame - Function encountered a FaceNotFoundError attempting to call FaceMesh.process().
2025-03-05 19:04:33,292 - pyfame.debug - ERROR - pyfame.py:645 - mask_face_region - Function has encountered an unparseable file type .webp. Consider using different input file formats, or transcoding video files with pyfameutils.transcode_video_to_mp4().
2025-03-05 19:05:46,925 - pyfame.debug - ERROR - pyfame.py:91 - process_frame - Function encountered a FaceNotFoundError attempting to call FaceMesh.process().
2025-03-05 19:05:46,942 - pyfame.debug - ERROR - pyfame.py:645 - mask_face_region - Function has encountered an unparseable file type .webp. Consider using different input file formats, or transcoding video files with pyfameutils.transcode_video_to_mp4().
2025-03-05 19:29:04,948 - pyfame.debug - ERROR - pyfame.py:81 - process_frame - Function encountered a FaceNotFoundError attempting to call FaceMesh.process().
2025-03-05 19:29:04,979 - pyfame.debug - ERROR - pyfame.py:635 - mask_face_region - Function has encountered an unparseable file type .webp. Consider using different input file formats, or transcoding video files with pyfameutils.transcode_video_to_mp4().
2025-03-05 19:29:21,299 - pyfame.debug - ERROR - pyfame.py:81 - process_frame - Function encountered a FaceNotFoundError attempting to call FaceMesh.process().
2025-03-05 19:29:21,323 - pyfame.debug - ERROR - pyfame.py:635 - mask_face_region - Function has encountered an unparseable file type .webp. Consider using different input file formats, or transcoding video files with pyfameutils.transcode_video_to_mp4().
2025-03-05 19:33:46,462 - pyfame.debug - ERROR - pyfame.py:79 - process_frame - Function encountered a FaceNotFoundError attempting to call FaceMesh.process().
2025-03-05 19:33:46,477 - pyfame.debug - ERROR - pyfame.py:633 - mask_face_region - Function has encountered an unparseable file type .webp. Consider using different input file formats, or transcoding video files with pyfameutils.transcode_video_to_mp4().
2025-03-05 19:34:01,182 - pyfame.debug - ERROR - pyfame.py:79 - process_frame - Function encountered a FaceNotFoundError attempting to call FaceMesh.process().
2025-03-05 19:34:01,197 - pyfame.debug - ERROR - pyfame.py:633 - mask_face_region - Function has encountered an unparseable file type .webp. Consider using different input file formats, or transcoding video files with pyfameutils.transcode_video_to_mp4().
